#!/bin/bash

set -eu

if [ -e /.os-migrate-toolbox ]; then
    echo "ERROR: You're already within an os-migrate toolbox container."
    echo "Calls to toolbox shouldn't be nested."
    exit 1
fi

if [ $(id -u) != 0 ]; then
   echo "ERROR: This must be run as root."
   echo "Due to Vagrant-libvirt permissions issues it is necessary "
   echo "to run Vagrant as root, to give it permissions for creating "
   echo "libvirt networks."
   exit 1
fi

DIR=$(dirname $(realpath $0))
PROJECT_DIR=$(realpath "$DIR")
if [ -t 1 ]; then
    CONTAINER_TTY_CREATE="${CONTAINER_TTY_CREATE:--ti}"
    CONTAINER_TTY_START="${CONTAINER_TTY_START:--i}"
else
    CONTAINER_TTY_CREATE="${CONTAINER_TTY_CREATE:-}"
    CONTAINER_TTY_START="${CONTAINER_TTY_START:-}"
fi

CONTAINER_IMAGE=${CONTAINER_IMAGE:-ghcr.io/os-migrate/os-migrate/os_migrate_toolbox:0.11.1}
# ROOTLESS_IMAGE_ID=$(podman inspect -f '{{.Id}}' $CONTAINER_IMAGE || true)
# ROOTFUL_IMAGE_ID=$(sudo podman inspect -f '{{.Id}}' $CONTAINER_IMAGE || true)
# if [ "$ROOTLESS_IMAGE_ID" != "$ROOTFUL_IMAGE_ID" ]; then
#     echo "Refreshing rootful image $CONTAINER_IMAGE..."
#     podman save $CONTAINER_IMAGE | sudo podman load
# fi

[ -e /usr/lib/passwd ] && USR_LIB_PASSWD="-v /usr/lib/passwd:/usr/lib/passwd:ro" || USR_LIB_PASSWD=""
[ -e /usr/lib/group ] && USR_LIB_GROUP="-v /usr/lib/group:/usr/lib/group:ro" || USR_LIB_GROUP=""

CONTAINER_NAME=hf_directord_vagrant

mkdir -p $HOME/.vagrant.d
mkdir -p $HOME/.cache/libvirt
mkdir -p $HOME/.config/libvirt
mkdir -p $HOME/.local/share/libvirt/vagrant

sudo podman create \
    --name $CONTAINER_NAME \
    $CONTAINER_TTY_CREATE \
    --net host \
    --pid host \
    --privileged \
    --security-opt label=disable \
    -u $UID:$UID \
    -v $HOME/.vagrant.d:$HOME/.vagrant.d \
    -v $HOME/.cache/libvirt:$HOME/.cache/libvirt \
    -v $HOME/.config/libvirt:$HOME/.config/libvirt \
    -v $HOME/.local/share/libvirt:$HOME/.local/share/libvirt \
    -v $PROJECT_DIR:$PROJECT_DIR \
    \
    -v /dev/net:/dev/net:rw \
    -v $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /etc/libvirt:/etc/libvirt:ro \
    -v /lib/modules:/lib/modules:ro \
    -v /run/libvirt:/run/libvirt:shared \
    -v /var/lib/libvirt:/var/lib/libvirt \
    $USR_LIB_PASSWD \
    $USR_LIB_GROUP \
    \
    -e LC_ALL=C.UTF-8 \
    -e HOME="$HOME" \
    -e SHELL="$SHELL" \
    -e XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
    -w "$PROJECT_DIR/vagrant" \
    ${VAGRANT_TOOLBOX_ARGS:-} \
    $CONTAINER_IMAGE \
    sleep infinity

CONTAINER_FS=$(sudo podman mount $CONTAINER_NAME)
if [ -z "$CONTAINER_FS" ]; then
    echo "ERROR: Empty container filesystem root path, cannot initialize the container."
    exit 1
fi
sudo mkdir -p "${CONTAINER_FS}${HOME}/.cache"
sudo mkdir -p "${CONTAINER_FS}${HOME}/.config"
sudo mkdir -p "${CONTAINER_FS}${HOME}/.local/share"
sudo mkdir -p "${CONTAINER_FS}${PROJECT_DIR}"
sudo chown -R "$USER:" "${CONTAINER_FS}${HOME}"

sudo podman start $CONTAINER_NAME

sudo podman exec -ti \
    --detach-keys='ctrl-^' \
    $CONTAINER_NAME \
    bash

