#!/bin/bash

set -euxo pipefail

if vagrant status | grep ^devstack | grep shutoff; then
   ./vagrant-up
fi

virsh snapshot-revert --domain hf_directord_node0 --snapshotname "${1:-clean}"
virsh snapshot-revert --domain hf_directord_node1 --snapshotname "${1:-clean}"
