- name: install packages for the hackfest
  ansible.builtin.package:
    name:
      - git
      - gcc
      - python3-pip
      - python3-devel
      - tmux
    state: present

- name: create stack user
  ansible.builtin.user:
    name: stack

- name: create sudoers entry for stack
  ansible.builtin.copy:
    dest: /etc/sudoers.d/stack
    content: |
      stack ALL=(ALL) NOPASSWD:ALL
